### PR TITLE
feat: async `generateStateFunction` and `checkStateFunction`

### LINKED ISSUE #238: [Feature Request] Async `generateStateFunction`
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

`generateStateFunction` can return a `Promise<string>`

### Motivation

I need to store the generated state in external databases like redis, and async operation is required here. But now the return value of `generateStateFunction` is directly passed to `reply.setCookie`.

### Example

```typescript
 fastify.register(oauthPlugin, {
   ...
   generateStateFunction: async (request) => {
      const [state, ctx] = await randomState();
      await redis.set(state, ctx);
      return state;
   }
 })
```

### PR DESCRIPTION
**Pull request by NotEvenANeko**
`generateStateFunction` and `checkStateFunction` now support async function, fastify instance can be accessed via `this`.

And the `generateAuthorizationUri` now returns a `Promise<string>` due to `generateStateFunction` can be async, which might be a breaking change.

close #238 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

#### Test results

```shell
❯ pnpm run test
> @fastify/oauth2@7.5.0 test
> npm run test:unit && npm run test:typescript


> @fastify/oauth2@7.5.0 test:unit
> tap

​ PASS ​ test/index.test.js 209 OK 292.476ms


                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   ​1 passed​, ​1 of 1 completed​
Asserts:  ​​​209 passed​, ​of 209​
​Time:​   ​622.737ms
​----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 index.js |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------

> @fastify/oauth2@7.5.0 test:typescript
> tsd

```

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add the new behavior to the docs?

**Comment by NotEvenANeko** [comment]
I forgot to push the commit yesterday, docs added.

**Comment by mcollina** [comment]
Can you update the branch? There are conflicts now.

**Comment by NotEvenANeko** [comment]
fixed

**Comment by mcollina** [comment]
I'm sorry, there are more conflicts :(

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
