### PR TITLE
Update: Typings

### PR DESCRIPTION
**Pull request by climba03003**
Resolve: #63
- reorganize typings
- update type checking

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by fox1t — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Eomm** [comment]
Would you mind to solve the conflicts?

Thks!

**Comment by climba03003** [comment]
All conflicts are solved.

**Review by Eomm — COMMENTED** [review]
@fox1t is this a major or patch?
I don't know how to evaluate this TS update

Maybe: would you like to release it with [releasify](https://github.com/fastify/releasify)?

```
# assuming GITHUB_TOKEN as env
releasify -s minor -n --npm-otp 123456
```

**Comment by fox1t** [comment]
Since this is just a Typings fix we can go for a patch too. It should break the build step if someone used the old one but it is still to be considered as a fix. 
Feel free to release this whenever you want!

**Pull request merged**
