### PR TITLE
major: upgrade to fastify v4

### PR DESCRIPTION
**Pull request by Eomm**

### CODE REVIEW

**Review by climba03003 — CHANGES_REQUESTED** [review]
Can you change the plugin meta `fastify` to `4.x`?

**Review by climba03003 — APPROVED** [review]
LGTM.

**Review by Fdawgs — APPROVED** [review]

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by mcollina** [comment]
I would actually prefer to land https://github.com/fastify/fastify-oauth2/issues/152 before this one and release together as a new major.

**Comment by climba03003** [comment]
> I would actually prefer to land #152 before this one and release together as a new major.

Can we cut a `next` branch and do all the works there? It wouldn't block the normal PR and release in this case.

**Comment by mcollina** [comment]
That'd be ok!

**Pull request merged**
