### PR TITLE
Improve out of the box types by using a prefix when decorating

### PR DESCRIPTION
**Pull request by voxpelli**
This enables out of the box typing + can, if the old way is eventually dropped, stop the risk of clashes between other fastify plugins and/or core methods and the names used in auth configurations.

Typing is achieved thanks to:

```ts
type UpperCaseCharacters = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z';

declare module 'fastify' {
    interface FastifyInstance {
        // UpperCaseCharacters ensures that the name has at least one character in it + is a simple camel-case:ification
        [key: `fastifyOauth2${UpperCaseCharacters}${string}`]: fastifyOauth2.OAuth2Namespace | undefined;
    }
}
```

The `UpperCaseCharacters` is a trick from [`type-fest`](https://github.com/sindresorhus/type-fest/blob/98bb74d3cbb73a71ed325cd984a754118ba4d054/source/internal.d.ts#L49)'s camel case helpers (which I contributed the first version of) and is used in its simplest form here for two reasons:

1. It ensures that `this.fastifyOauth2` is not matched, something it would be with `fastifyOauth2${string}`
2. It makes it look somewhat prettier, making a name like `google` become `this.fastifyOauth2Google`

In this PR I have changed the docs to prefer the new prefixed properties, but I have kept the old decoration as well, to not break implementations for now.

#### Checklist

- [x] run `npm run test` ~~and `npm run benchmark`~~
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
I would just go with `oauth2` prefix, dropping fastify.

Extremely good work, thx!

**Comment by voxpelli** [comment]
> I would just go with `oauth2` prefix, dropping fastify.

Done!

> Extremely good work, thx!

Thanks!

**Comment by Uzlopak** [comment]
Why the prefixing if you only add an attribute oauth2?

**Comment by Uzlopak** [comment]
Ah ok, you assign more

**Comment by Uzlopak** [comment]
Why do we assign it twice? 

@mcollina 
How about breaking change, and just decorate the fastify instance with the `oauth2${namespace}`.

**Comment by Eomm** [comment]
> Why the prefixing if you only add an attribute oauth2?

Still: why?
It is a cosmetic thing that hurts every CTRL+F or search tool - I don't like it

**Comment by voxpelli** [comment]
> > Why the prefixing if you only add an attribute oauth2?
> 
> Still: why? It is a cosmetic thing that hurts every CTRL+F or search tool - I don't like it

@Eomm Because we can't do:

```ts
interface FastifyInstance {
    [key: string]: OAuth2Namespace | undefined;
}
```

As that would indicate that all properties on `FastifyInstance` are `OAuth2Namespace`:s

But we can do:


```ts
interface FastifyInstance {
    [key: `oauth2${string}]: OAuth2Namespace | undefined;
}
```

As that says that all properties on `FastifyInstance` with an `oauth2` prefix are `OAuth2Namespace`:s.

Currently a user of this module needs to themselves instead add something like this for TypeScript to not complain, which I don't think they shouldn't need to:

```ts
interface FastifyInstance {
    customOauth2: OAuth2Namespace;
}
```

(There's also a risk of collision, if one eg. has a github plugin that adds a `github` decorator and then wants to use an auth configuration for `github` as well, then the two will unexpectedly clash, whereas with a prefix the likelihood of unexpected clashes are reduced a lot. Though this would only be mitigated if doing this as the breaking change that @Uzlopak is suggesting)

**Comment by Uzlopak** [comment]
What i did for jwt was implementing a helper type

https://github.com/fastify/fastify-jwt/pull/303

I like my approach of course more. ;)

Benefit is that the typescript engine does not need to check attributes by patterns. This can get slow.

**Comment by voxpelli** [comment]
@Uzlopak Such a solution would provide little benefit over the current solution here I think? It would still be as manual?

```ts
interface FastifyInstance {
    customOauth2: OAuth2Namespace;
}
```

vs

```ts
interface FastifyInstance extends FastifyOauth2Namespace<'customOauth2'> {
}
```

Whereas what I propose here requires no actual type additions unless one would actually want to increase some discoverability and avoid the `| undefined`.

(My ideal solution would be to have a single instance of `fastify-oauth2` registered, with multiple auth configurations, rather than one for every auth configuration. That would enable a single getter decorator for access to all of the auth configurations – but that would be a major undertaking and something I will do through a wrapper instead)

**Comment by Uzlopak** [comment]
What i prefer from the namespace type helper is that I dont need to expose alot of internals.

Maybe the jwtNamespace helper is perfect for fastify/jwt case and not for this plugin. 

Also isnt there a Uppercase Type already in ts?

**Comment by voxpelli** [comment]
> Maybe the jwtNamespace helper is perfect for fastify/jwt case and not for this plugin.

Well, this PR is about removing the need for adding any type manually rather than about improving how to add it manually, but yeah, it differs since `@fastify/oauth2` is meant to be added once for every auth configuration and if one adds eg. Google, Facebook and GitHub then it will add three side by side decorations, whereas `@fastify/jwt` is only meant to be added once and where you only modify the decorator names in case of a clash with another module.

> Also isnt there a Uppercase Type already in ts?

There is [`Capitalize<>`](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#capitalizestringtype) and it actually seems like this would mostly work:

```ts
interface FastifyInstance {
    [key: `oauth2${Capitalize<string>}`]: OAuth2Namespace | undefined;
}
```

One downside compared to the `oauth2${UpperCaseCharacters}${string}` solution is that it doesn't enforce a minimum length of the name, so also `fastify.oauth2` itself would get the type `OAuth2Namespace | undefined`, which feels wrong and like it could cause confusion.

**Comment by Eomm** [comment]
@voxpelli Thanks for explaining, but I think you already know my opinion: TS should bend to JS and not vice-versa. But I'm biased, and I step back from the PR review: no blocking at all if others think it improves the dev experience.

I'm unsure if this code can be avoided if the plugin is registered in `file1.ts` and then `fastify.oauth2CustomOauth2` is accessed in another plugin at `file2.ts`.
Does this PR solve this use case too?

```
interface FastifyInstance {
    customOauth2: OAuth2Namespace;
}
```

**Comment by mcollina** [comment]
I think I would rather have a `app.oauth2.github` and a single decorator than multiple ones. It would actually make things simpler  for consumer of multiple providers (or when the provider is parametrized).

If we need to add a _second_ way to avoid a breaking change, I recommend doing that.

**Comment by voxpelli** [comment]
@mcollina I agree, that was my initial idea, but since this plug-in is meant to be added once for every auth configuration I each instance owns it’s own decoration and sharing one decorator between many plug-in instances – I’m not sure how to do that in a good way. Suggestion?

As I think I wrote earlier in here I would personally wish for this plug-in to accept multiple auth configurations in a single instance, removing the need for multiple plug-in instances and simplifying having a single decorator for them all

**Comment by voxpelli** [comment]
To exemplify my last comment:

When registered like this I don't know how to easily share a single decorated value between them:

```js
fastify.register(oauthPlugin, {
  name: 'facebookOAuth2',
  credentials: {
    client: { id: '<CLIENT_ID>', secret: '<CLIENT_SECRET>' },
    auth: oauthPlugin.FACEBOOK_CONFIGURATION
  },
  startRedirectPath: '/login/facebook',
  callbackUri: 'http://localhost:3000/login/facebook/callback'
});

fastify.register(oauthPlugin, {
  name: 'githubOAuth2',
  credentials: {
    client: { id: '<CLIENT_ID>', secret: '<CLIENT_SECRET>' },
    auth: oauthPlugin.GITHUB_CONFIGURATION
  },
  startRedirectPath: '/login/github',
  callbackUri: 'http://localhost:3000/login/github/callback'
});
```

When registered like this it would be very easy to do `app.oauth2.githubOAuth2`:

```js
fastify.register(oauthPlugin, {
  someGoodNameForAConfigurationParameter: [
    {
      name: 'facebookOAuth2',
      credentials: {
        client: { id: '<CLIENT_ID>', secret: '<CLIENT_SECRET>' },
        auth: oauthPlugin.FACEBOOK_CONFIGURATION
      },
      startRedirectPath: '/login/facebook',
      callbackUri: 'http://localhost:3000/login/facebook/callback'
    },
    {
      name: 'githubOAuth2',
      credentials: {
        client: { id: '<CLIENT_ID>', secret: '<CLIENT_SECRET>' },
        auth: oauthPlugin.GITHUB_CONFIGURATION
      },
      startRedirectPath: '/login/github',
      callbackUri: 'http://localhost:3000/login/github/callback'
    }
  ]
});
```

**Comment by mcollina** [comment]
The core idea for this plugin is to have it registered once for each one of the providers

**Comment by voxpelli** [comment]
> The core idea for this plugin is to have it registered once for each one of the providers

@mcollina Yes, and then I think the solution I propose in this PR is the appropriate one as they can't easily share a single decorator then 🙂

**Comment by Uzlopak** [comment]
I have no strong opinion on this.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
