### PR TITLE
Added Twitch Defaults

### PR DESCRIPTION
**Pull request by LKNSI**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by climba03003 — CHANGES_REQUESTED** [review]
Can you add the type in https://github.com/fastify/fastify-oauth2/blob/master/index.d.ts#L12
And unit test for type in https://github.com/fastify/fastify-oauth2/blob/master/index.test-d.ts#L59

**Review by jsumners — APPROVED** [review]

**Review by Eomm — APPROVED** [review]
LGTM with @climba03003 suggestion

**Comment by Sense** [comment]
Any news from this one @LKNSI ?

**Comment by mcollina** [comment]
@Sense would you like to send a fresh PR?

**Comment by Sense** [comment]
> @Sense would you like to send a fresh PR?

definitely. Will do asap.

**Review by LKNSI — COMMENTED** [review]
Updated to include TS

**Review by LKNSI — COMMENTED** [review]
Typo

**Review by climba03003 — APPROVED** [review]
LGTM.

**Pull request merged**
