### PR TITLE
Added Microsoft Online configuration

### PR DESCRIPTION
**Pull request by lmammino**
Added Microsoft Online configuration

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] ~~tests and/or benchmarks are included~~
- [ ] ~~documentation is changed or added~~
- [X] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by allevo** [comment]
Published: 2.2.0 is out!

**Comment by lmammino** [comment]
Thanks :)

**Comment by lmammino** [comment]
Does this get automatically published to NPM?

**Comment by allevo** [comment]
Nope, I have published it to npm manually
https://www.npmjs.com/package/fastify-oauth2

**Comment by Eomm** [comment]
If you have 5 min, check out the [releasify](https://www.npmjs.com/package/releasify) so we will have the release in GH with the changelog 👍

**Pull request merged**
