### PR TITLE
[Fix] The decorator 'getAccessTokenFromAuthorizationCodeFlow' 

### PR DESCRIPTION
**Pull request by lagmanzaza**
I found an issue that is a solution so I create this PR #9 

Thank you `ekuzu` comment solution

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test?

**Comment by Eomm** [comment]
@lagmanzaza are you willing to add a unit test in order to merge this PR? 💪

**Comment by lagmanzaza** [comment]
I'm so sorry that I forgot to reply to all of you.

I think that #17  it's better than my pull request

**Comment by lagmanzaza** [comment]
I think that you should merge #17 to this repo ^_^

**Pull request closed without merging**
