### PR TITLE
Update for Fastify v5

### PR DESCRIPTION
**Pull request by synapse**
Ref: https://github.com/fastify/fastify/issues/5116

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

CC @simoneb

### CODE REVIEW

**Comment by synapse** [comment]
⚠️ we might need a new `next` branch for this one

**Comment by simoneb** [comment]
interesting that no tests are being triggered though

**Comment by synapse** [comment]
> interesting that no tests are being triggered though

Hmm, on my repo/branch they where run and all passed 🤔

**Comment by simoneb** [comment]
can you check why they're not triggering here?

**Review by Fdawgs — APPROVED** [review]

**Pull request merged**
