### PR TITLE
feat: add vatsim configuration setup

### PR DESCRIPTION
**Pull request by Enrico1108**
Hello my last PR had an error in the index.d.ts file, I made the correction and added code examples
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Enrico1108** [comment]
Run all tests and passed

**Comment by mcollina** [comment]
please add an assertion for vatsim in https://github.com/fastify/fastify-oauth2/blob/14b162c81b2951dbfe4044644c4c001b84a18fa5/test/types/index.test-d.ts#L59

**Comment by Enrico1108** [comment]
Done @mcollina

**Review by darkgl0w — APPROVED** [review]
lgtm

**Comment by Enrico1108** [comment]
Do you have an estimate of when I will be able to download this version that I added Vatsim Auth to my project?

**Review by mcollina — APPROVED** [review]
lgtm - will ship as somebody has time to cut a release

**Comment by Enrico1108** [comment]
correct! thank you!

**Pull request merged**
